name: Heinrich Reimer
description: Android development with love.
license: All rights reserved.
url: https://heinrichreimer.com
author:
  name: Heinrich Reimer
  adress:
    street: Turmfalkenweg 1
    zip: 38124
    city: Braunschweig
    country: Germany
  email: heinrich@heinrichreimer.com
  telephone: +49 1749273954

meta:
  title: Heinrich Reimer
  description: Android development with love.

collections:
- apps
- libraries
- websites
- services

defaults:
  - scope:
      path: ""
      type: apps
    values:
      layout: page
  - scope:
      path: ""
      type: libraries
    values:
      layout: page
  - scope:
      path: ""
      type: websites
  - scope:
      path: ""
      type: services
    values:
      layout: page

compress_html:
  clippings: [div, p, ul, td, h1, h2]
  comments: ["<!-- ", " -->"]
  endings: [li, td]
  startings: [html, head, body]

markdown: kramdown

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
