name: Heinrich Reimer
markdown: kramdown
author: Heinrich Reimer
license: All rights reserved.
url: https://heinrichreimer.com

meta:
  title: Heinrich Reimer
  description: Android development with love.
