# Meta information
name: Heinrich Reimer
description: Android development with love.
license: All rights reserved.
url: https://heinrichreimer.com
author:
  name: Heinrich Reimer
  adress:
    street: Turmfalkenweg 1
    zip: 38124
    city: Braunschweig
    country: Germany
  email: heinrich@heinrichreimer.com
  telephone: +49 1749273954

# Collections of posts
collections:
- apps
- libraries
- websites
- services

# Needed to include CSS/JS inline
includes:
- res
- bower_components/webcomponentsjs

# Removes files and folders from Jekyll build
exclude:
- node_modules
- bower.json
- README.md

# Default values
defaults:
  - scope:
      path: ""
    values:
      layout: page

# HTML compressor configurations
compress_html:
  clippings: [div, p, ul, td, h1, h2, h3, h4, h5, h6, hr]
  comments: ["<!-- ", " -->"]
  endings: [li, td]
  startings: [html, head, body]
  ignore:
    envs:
      development

# Markdown parser
markdown: kramdown

# Jekyll plugins
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
