# Meta information
title: Heinrich Reimer
description: Android development with love.
license: All rights reserved.
logo: /res/images/logos/logo_brand.png
url: https://heinrichreimer.github.io
# url: https://heinrichreimer.com # TODO Use in production
author:
  name: Heinrich Reimer
  adress:
    street: Barfüßerstraße 7
    zip: 06108
    city: Halle (Saale)
    country: Germany
  email: heinrich@heinrichreimer.com
  telephone: "+49 1749273954"
  twitter: Kieselstein000
  google_plus: HeinrichReimer
twitter:
  username: Kieselstein000
social:
  name: Heinrich Reimer
  links:
    - https://twitter.com/Kieselstein000
    - https://www.facebook.com/HeinrichReimer
    - https://plus.google.com/+HeinrichReimer
    - https://github.com/HeinrichReimer
    - https://www.linkedin.com/in/heinrich-reimer-680877120
    - https://www.xing.com/profile/Heinrich_Reimer3
    - http://stackoverflow.com/users/2037482/heinrich
webmaster_verifications:
  google: 5mySK6jpuoQ7RT2vFF-GKGFtb4FWZwxLZ4aBcLwvUdw
  bing: 3653BD8AC68D24520E97C345142CC6FA
host: github
# host: uberspace # TODO Use in production
keywords:
- Android
- Development
- Web
- Webdesign
- Consulting
- Freelancer
- Heinrich
- Reimer
- Apps
- Libraries
- Open-Source
- GitHub
- Websites
- Java
- CSS
- Markdown
- User Interface

# Collections of posts
collections:
- apps
- libraries
- websites
- services

# Removes files and folders from Jekyll build
exclude:
- node_modules
- bower.json
- README.md
- vendor

# Default values
defaults:
  - scope:
      path: ""
    values:
      layout: page
      image:
        path: /res/images/banners/default.png
        twitter: /res/images/banners/twitter.png
        facebook: /res/images/banners/facebook.png
  - scope:
      path: "/bower_components/"
    values:
      sitemap: false
  - scope:
      path: "/bower_components"
    values:
      sitemap: false
  - scope:
      path: "bower_components/"
    values:
      sitemap: false
  - scope:
      path: "bower_components"
    values:
      sitemap: false

# HTML compressor configurations
compress_html:
  clippings: [div, p, ul, td, h1, h2, h3, h4, h5, h6, hr]
  comments: ["<!-- ", " -->"]
  endings: [li, td]
  startings: [html, head, body]
  ignore:
    envs:
      development

# Markdown parser
markdown: kramdown

# Jekyll plugins
gems:
  # will be executed top to bottom
  - jemoji
  - jekyll-gist
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-titles-from-headings
  - jekyll-seo-tag
  - jekyll-redirect-from
  # - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

