title: "Jan Heinrich Reimer"
baseURL: "https://heinrichreimer.com/"
languageCode: "en-us"

metaDataFormat: "yaml"
defaultContentLanguage: "en-us"
enableRobotsTXT: true
disableKinds:
  - taxonomies
  - taxonomyTerm

menu:
  footer:
  - identifier: source
    name: Source
    url: https://github.com/heinrichreimer/portfolio
    weight: 3

sitemap:
  changeFreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

params:
  env: production
