title: Jan Heinrich Merker
baseURL: https://heinrich.merker.id/

defaultContentLanguage: en
languages:
  en:
    weight: 1
    languageCode: en-de
    languageName: English
    menu:
      footer:
        - identifier: source
          name: Source
          url: https://github.com/janheinrichmerker/website
          weight: 3
  de:
    weight: 2
    languageCode: de-de
    languageName: German (Germany)
    menu:
      footer:
        - identifier: source
          name: Quellcode
          url: https://github.com/janheinrichmerker/website
          weight: 3


params:
  env: production
  colors:
    theme: "#052561"
    background: "#ffffff"

timeout: 300s
metaDataFormat: yaml
enableEmoji: true
enableRobotsTXT: true

disableKinds:
  - taxonomy

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      table: true
      strikethrough: true
      linkify: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    style: friendly

sitemap:
  changeFreq: monthly
  priority: 0.5
  filename: sitemap.xml

caches:
  getcsv:
    maxAge: 24h
  getjson:
    maxAge: 24h
  getresource:
    maxAge: 24h
