title: "Jan Heinrich Reimer"
baseURL: "https://heinrichreimer.eu/"
metaDataFormat: "yaml"
disableKinds:
  - taxonomies
  - taxonomyTerm

enableEmoji: true
enableRobotsTXT: true
enableGitInfo: true

defaultContentLanguage: "en"
languageCode: "en-us"
languageName: "English (United States)"

menu:
  footer:
  - identifier: source
    name: Source
    url: https://github.com/heinrichreimer/portfolio
    weight: 3

sitemap:
  changeFreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

params:
  env: production
