language: ruby
rvm:
  - 2.3.3
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # Speeds up installation of html-proofer

cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

before_script:
  - chmod +x ./scripts/cibuild.sh
  - chmod +x ./scripts/deploy.sh

# Assume bundler is being used, therefore the `install` step will run `bundle install` by default.
script:
  - bower install
  - ./scripts/cibuild.sh

deploy:
  # Deploy master to GitHub Pages
  - provider: pages
    local-dir: ./_site
    keep-history: true
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    on:
      branch: master
  # Deploy master to production
  - provider: script
    script: ./scripts/deploy.sh
    on:
      branch: master

sudo: false # Route your build to the container-based infrastructure for a faster build
